# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16rry9irf0HiMpEKod4GNBMVdIiJVWAR1

***Mini Project of Environmental Data Analyst (using Python) for analysizing Air Quality data from EPA***

**1. Install libraries**
"""

!pip install pandas numpy matplotlib seaborn

"""**2. Looking out Air Quality dataset and Preprocess data**

data retrieved from EPA outdoor air quality. You can check from: https://www.epa.gov/outdoor-air-quality-data/download-daily-data (I use dataset of pollutant PM 2.5 from New York area in 2026)
"""

import pandas as pd
df = pd.read_csv('aq_viz_plotval_newyork_2026_data.csv')

print(df.head())

print(df.info())
print(df.describe())
print(df.isnull().sum())

df=df.dropna()

df['Date']=pd.to_datetime(df['Date'])

"""3. Graphing Air Quality Index (AQI) data"""

import matplotlib.pyplot as plt
import seaborn as sbn
sbn.set(style="darkgrid")

#plot AQI vs time
plt.figure(figsize=(15,8))
sbn.lineplot(x='Date', y='Daily AQI Value', data=df, marker='o')
plt.title('AQI Over Time')
plt.xlabel('Date')
plt.ylabel('AQI')
plt.xticks(rotation=60)
plt.tight_layout()
plt.show()

"""**4. Graphing AQi vs PM2.5 Concentration**"""

#plot AQI vs PM2.5
plt.figure(figsize=(15,8))
sbn.lineplot(x='Daily Mean PM2.5 Concentration', y='Daily AQI Value', data=df, marker='o')
plt.title('AQI vs PM2.5 Concentration')
plt.xlabel('Daily PM2.5 Concentration')
plt.ylabel('Daily AQI Value')
plt.xticks(rotation=60)
plt.tight_layout()
plt.show()

"""**5. Linear Regression plot to evaluate AQI vs PM2.5 correlation**"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

#Prepare data to learn regression
x=df[['Daily Mean PM2.5 Concentration']].values
y=df['Daily AQI Value'].values

#Create and Fit the Model
model=LinearRegression()
model.fit(x,y)

#Predict AQI values
y_pred=model.predict(x)

#Calculate R2
r2=r2_score(y,y_pred)
print(f'R^2 value:{r2:.3f}')

plt.figure(figsize=[11,7])

#Scatter Plot
sbn.scatterplot(x='Daily Mean PM2.5 Concentration', y='Daily AQI Value', data=df, color='red', label='Data')

#Regression Line
sbn.lineplot(x=df['Daily Mean PM2.5 Concentration'], y=y_pred, color='green', label='Regression Line')
plt.title(f'AQI vs PM 2.5 value (R^2 value:{r2:.4f})')
plt.xlabel('PM2.5 Concentration')
plt.ylabel('AQI Value')
plt.xticks(rotation=30)
plt.legend()
plt.show()

"""**6. Comparing AQI data between different years (2020 vs 2026)**"""

#2020
df_2020= pd.read_csv('aq_viz_plotval_newyork_2020_data.csv')
print('2020 Data Head:')
display(df_2020.head())

#2026
df_2026= pd.read_csv('aq_viz_plotval_newyork_2026_data.csv')

df_2020['Date'] = pd.to_datetime(df_2020['Date'])
df_2026['Date'] = pd.to_datetime(df_2026['Date'])

#Extract Day and Month
df_2020['Month_Day'] = df_2020['Date'].dt.strftime('%m-%d')
df_2026['Month_Day'] = df_2026['Date'].dt.strftime('%m-%d')

plt.figure(figsize=[13,9])

#Plot Year of 2020
sbn.scatterplot(x='Month_Day', y='Daily AQI Value', data=df_2020, color='blue', label='2020', alpha=0.6)
#Plot Year of 2026
sbn.scatterplot(x='Month_Day', y='Daily AQI Value', data=df_2026, color='red', label='2026', alpha=0.5)
plt.xticks(rotation=45)
plt.title(f'Daily AQI vs Month-Day for 2 different year (2020 vs 2026)')
plt.xlabel('Month-Day')
plt.ylabel('Daily AQI')
plt.xticks(rotation=30)
plt.legend()
plt.show()

df_2020['Month']=df_2020['Date'].dt.month
df_2020['Year'] = df_2020['Date'].dt.year

df_2026['Month']=df_2026['Date'].dt.month
df_2026['Year'] = df_2026['Date'].dt.year

#Calculate Monthly Average AQI for each year
monthly_avg_2020 = df_2020.groupby(['Year','Month'])['Daily AQI Value'].mean().reset_index()
monthly_avg_2026 = df_2026.groupby(['Year','Month'])['Daily AQI Value'].mean().reset_index()

plt.figure(figsize=[13,9])

#Plot Year of 2020
sbn.lineplot(x='Month', y='Daily AQI Value', data=monthly_avg_2020, color='blue', label='2020', marker='o')
#Plot Year of 2026
sbn.lineplot(x='Month', y='Daily AQI Value', data=monthly_avg_2026, color='red', label='2026', marker='o')

plt.title(f'Monthly Average AQI for 2 different years (2020 vs 2026)')
plt.xlabel('Month')
plt.ylabel('Monthly Average AQI')
plt.xticks(ticks=range(1,13), labels=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
plt.legend()
plt.show()

"""**7. Graphing NO2 data**"""

df_NO2_2026= pd.read_csv('ad_viz_NO2_newyork_2026.csv')
df_NO2_2026['Date'] = pd.to_datetime(df_NO2_2026['Date'])
print(df_NO2_2026.head())

sbn.set(style="darkgrid")
plt.figure(figsize=[13,9])
sbn.lineplot(x='Date', y='Daily Max 1-hour NO2 Concentration', data=df_NO2_2026, color='blue', label='2026', marker='o')
plt.title('Daily Max 1-hour NO2 Concentration')
plt.xlabel('Date')
plt.ylabel('NO2 Concentration')
plt.xticks(rotation=45)
plt.legend()
plt.show()

"""**8. Graphing CO gas data**"""

df_CO_2026= pd.read_csv('ad_viz_CO_newyork_2026.csv')
df_CO_2026['Date'] = pd.to_datetime(df_CO_2026['Date'])
print(df_CO_2026.head())

sbn.set(style="darkgrid")
plt.figure(figsize=[13,9])
sbn.lineplot(x='Date', y='Daily Max 8-hour CO Concentration', data=df_CO_2026, color='black', label='2026', marker='o')
plt.title('Daily Max 8-hour CO Concentration')
plt.xlabel('Date')
plt.ylabel('CO gas Concentration')
plt.xticks(rotation=30)
plt.legend()
plt.show()